FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN node ace build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/build ./
RUN npm install --omit=dev
EXPOSE 3333
CMD ["node", "bin/server.js"]