/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Cursos: () => import('#controllers/cursos_controller'),
  Estudantes: () => import('#controllers/estudantes_controller'),
  Notas: () => import('#controllers/notas_controller'),
}
